# Generated by Django 3.0.8 on 2020-07-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_webapps'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapps',
            name='status',
            field=models.CharField(choices=[('R', 'Reviewed'), ('N', 'Not Reviewed'), ('A', 'Accepted'), ('E', 'Error')], default='R', max_length=1),
            preserve_default=False,
        ),
    ]
